### ISSUE TITLE
Customization: Allow different completion texts depending on the path

### ISSUE THREAD

**Issue by reginafcompton** [datamade/rapidsms-decisiontree-app#3]

**Comment by fgregg** [comment]
This violates the idea of a state machine. If you want to emit different questions, those should be different states.

**Comment by reginafcompton** [comment]
PR #2 closes this issue....and I see now how the wording of the issue is confusing. 

Issue should read: "Send user a particular completion text when arriving at a terminal state - determined by looking for a transition set"
