### ISSUE TITLE
Customization: Render the questions AND answers in a nice way

### ISSUE THREAD

**Issue by reginafcompton** [datamade/rapidsms-decisiontree-app#4]
By default the decisiontree app sends the user the question only. We want the user to see the numerated answer options, in a clean easy-to-read message.

**Comment by fgregg** [comment]
Why can't the numerated answer options be a part of question?

**Comment by reginafcompton** [comment]
Sure, that's one solution, and I think we can pass in line breaks between answers (so that the user does not receive one giant block of text).

**Comment by fgregg** [comment]
Why wouldn't this be the preferred solution?

**Comment by reginafcompton** [comment]
Well, the app does make use of Answer objects, e.g., to know how to get from state to state. If we also put those answers in the Question object, then we'd need to keep track of the answer data in two places.

**Comment by fgregg** [comment]
The answer object isn't the User's answer?

**Comment by reginafcompton** [comment]
No, we have to create Answer objects, which are necessary for telling the app how to move from state to state: https://github.com/datamade/rapidsms-decisiontree-app/blob/master/decisiontree/models.py#L184

**Comment by fgregg** [comment]
got it. okay, let's go with the flow of the library then for, now.

**Comment by reginafcompton** [comment]
Closed via PR #6
